### ISSUE TITLE
DimensionalTrees

### ISSUE THREAD

**Issue by werken23** [BentoBoxWorld/TwerkingForTrees#10]
#### Describe the bug

DimensionalTrees are unable to grow by twerking.

#### Steps to reproduce the behavior

1. have both TwerkingForTrees and DimensionalTrees installed and configurated
2. place a sapling in the nether or end and twerk near it

#### Expected behavior

TwerkingForTrees should detect if DimensionalTrees is installed and place the correct dimensional tree.

##### BentoBox Version (Mandatory)

```
09.02 22:49:03 [Server] INFO Running PAPER 1.15.2.
09.02 22:49:03 [Server] INFO BentoBox version: 1.11.0
09.02 22:49:03 [Server] INFO Database: JSON
09.02 22:49:03 [Server] INFO Loaded Game Worlds:
09.02 22:49:03 [Server] INFO skyblock_world (SkyBlock): Overworld, Nether, [end_color]End
09.02 22:49:03 [Server] INFO Loaded Addons:
09.02 22:49:03 [Server] INFO Biomes 1.6.0.1 (ENABLED)
09.02 22:49:03 [Server] INFO BSkyBlock 1.11.0 (ENABLED)
09.02 22:49:03 [Server] INFO Challenges 0.8.0 (ENABLED)
09.02 22:49:03 [Server] INFO ControlPanel 1.7.0 (ENABLED)
09.02 22:49:03 [Server] INFO DimensionalTrees 1.6.0 (ENABLED)
09.02 22:49:03 [Server] INFO ExtraMobs 1.11.0.2 (ENABLED)
09.02 22:49:03 [Server] INFO IslandFly 1.7.0 (ENABLED)
09.02 22:49:03 [Server] INFO Level 1.9.3 (ENABLED)
09.02 22:49:03 [Server] INFO Likes 1.7.0 (ENABLED)
09.02 22:49:03 [Server] INFO Limits 1.9.0 (ENABLED)
09.02 22:49:03 [Server] INFO MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
09.02 22:49:03 [Server] INFO TwerkingForTrees 1.1.2 (ENABLED)
```

**Comment by tastybento** [comment]
The API call used to grow trees does not allow growing trees in the nether. It's not clear why, but in 1.15.2 isn't not possible. So right now, twerking for trees doesn't work in the nether. It's sort of a bug, but I'm not sure how to fix right now.

**Comment by hnedokneznik** [comment]
Hello, can you add the option to turn off twerking in nether and end?

**Comment by tastybento** [comment]
As it doesn't seem possible to spawn trees in the nether or end via API I'll disable it completely for now. Overworld only.
