### ISSUE TITLE
Allow sprinting near a sapling to have the same affect.

### ISSUE THREAD

**Issue by johncsuti** [BentoBoxWorld/TwerkingForTrees#14]
#### Is your feature request related to a problem?

Nope.

#### Describe the solution you'd like us to implement.

Add a hook to tell if there is a sapling on island and if the player is sprinting to cause the same affect as twerking.

#### Describe alternatives you've considered.

None.

### Additional context

None.

**Comment by johncsuti** [comment]
I kinda can't believe this isn't added by now. Its alright to not add it if its just too much work.

**Comment by tastybento** [comment]
Done - at last...
