### ISSUE TITLE
Twerkin bugg with some blocks near

### ISSUE THREAD

**Issue by Teyir** [BentoBoxWorld/TwerkingForTrees#20]
#### Describe the bug
When we have some blocks near the saplings the saplings change in oak 

#### Steps to reproduce the behavior
This is the GIF with the bugg
[http://teyir.fr/img/bugg-twerk.gif](http://teyir.fr/img/bugg-twerk.gif)

This is the bbox version https://prnt.sc/t00klw

This is my paper version https://prnt.sc/t00l80

**Comment by tastybento** [comment]
This is due to vanilla tree growing - if the big tree cannot grow because of blocks close by it will ultimately grow as just a default oak tree. With your version of Twerking you lost the other saplings. Upgrade to the latest version (1.4.0) and you won't loose your other 3 saplings.
