### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by S1iwa** [BentoBoxWorld/TwerkingForTrees#21]
#### Describe the bug
Saplings grow faster only when thay "see" sky
And that's why this addon is useless on caveblock

#### Steps to reproduce the behavior
Set sapling on grass block and just spam shift on caveblock
If you make a tunnel to sky, this would work

#### Expected behavior
Saplings should alwase grow

#### Screenshots and videos (Optional)
https://drive.google.com/file/d/1Jk6G14eHgwvDLCjOsXqXDvB3jx2R6W5H/view?usp=sharing

##### Output of `/bbox version` (Mandatory)

```
[Mon, 1. Mar 2021 21:20:46 CET INFO] Bank 1.3.0 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] Biomes 1.14.0 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] CaveBlock 1.14.2 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] Challenges 0.8.3 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] ControlPanel 1.7.0 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] DimensionalTrees 1.6.0 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] Level 2.6.0 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] Limits 1.15.5 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] MagicCobblestoneGenerator 2.2.1 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] TwerkingForTrees 1.4.1 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] Upgrades 0.2.0-SNAPSHOT-b80 (ENABLED)
[Mon, 1. Mar 2021 21:20:46 CET INFO] Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (35): AdvancedBan*, AdvancedHelp, AuctionHouse, BentoBox, BungeeTabListPlus, ChatManager, ChatReaction, ChestShop, CoreProtect, DiscordSRV, DynamicShop, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, GSit, HolographicDisplays, LuckPerms, MysqlPlayerDataBridge, NexEngine, OnlineTime, OpenInv, PacketLimiter, ProtocolLib, SilkSpawners, SkinsRestorer, spark, TradeSystem, UltimateAutoRestart, Vault, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags
```
 
### Additional context (Optional)
none

**Comment by tastybento** [comment]
I think the issue is that you have quads of trees - four of them next to each other. That then tries to generate a large tree. However, there isn't room to do that, - the cave is not tall enough. Now, there is one type of big tree that is just a normal tree but it is very rare, so that is what grows.

Try the same experiment, but with just one sapling, or move your saplings so they are at least 4 block apart.

Also, the rules about generating trees is governed by the server, so it'll be really hard to change the behavior because it is just vanilla growing that is being used.

**Comment by S1iwa** [comment]
Oh I did a lot of free space and it really works
Thanks

**Comment by S1iwa** [comment]
Ok nevermind
It still doesnt work
https://drive.google.com/file/d/1kNONc1N0i3ksbhG6FiPw56tbBPrJ37Qp/view?usp=sharing

**Comment by tastybento** [comment]
Twerking doesn't break the server rules for tree growth, so go into creative and see if you can get it to grow using bonemeal. If you can't then twerking won't do it either. I googled "Minecraft growing trees underground" and it seems you need 7 blocks above for a single tree, more if you do the bigger trees.

**Comment by S1iwa** [comment]
When i'm using bonemeal everything is ok

**Comment by tastybento** [comment]
Try this debug version. It'll report to the console. I'd like to see what it says in the console, so copy and paste after you try and do some twerking.
[TwerkingForTrees-1.4.1-SNAPSHOT-LOCAL.jar.zip](https://github.com/BentoBoxWorld/TwerkingForTrees/files/6081043/TwerkingForTrees-1.4.1-SNAPSHOT-LOCAL.jar.zip)

**Comment by johncsuti** [comment]
Don't all trees need sky access in order to grow or am i mistaken on that?
