### ISSUE TITLE
Allow an option to grow trees by holding, instead of spamming, sneak

### ISSUE THREAD

**Issue by User670** [BentoBoxWorld/TwerkingForTrees#27]
### Is your feature request related to a problem?

Yes and no. It's an accessibility thing.

For players who have mobility issues that make them hard to spam a key quickly, or players using a control scheme that make them hard to spam sneak quickly (eg, using "toggle" instead of "hold" for Sneak require them to press the key 2 times for a single sneak-and-stand-up action; Bedrock players on a touch screen need to press an on-screen button 4 times for a single sneak-and-stand-up action), requiring them to spam sneak can be annoying and place them at a disadvantage.

### Describe the solution you'd like.

Add an option that allows players to hold sneak around trees to speed up the growth. For example, attempt to grow trees for every 2 seconds sneaking.

A server/admin-side config option should be added for enabling and disabling this feature. Additionally, a player-side option could be added for players to opt-in/out of this, in case a player finds this unfavorable (eg, sneaking around when building accidentally grows a tree)

### Describe alternatives you've considered.

A server/admin-side toggle and player-side opt-in for sneaking less times to grow trees?

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

Related-ish issue: #14

Also, feel free to disregard this and call this a player problem. I won't complain.

**Comment by BONNe** [comment]
There is a new addon called FarmersDance. It has that option.
I am not sure if TwerkingForTrees will get one.

**Comment by tastybento** [comment]
Done (at last)
