### ISSUE TITLE
Twerking for Trees is not growing trees - Minecraft 1.20.2

### ISSUE THREAD

**Issue by Barevoss** [BentoBoxWorld/TwerkingForTrees#28]
### Expected behavior

expect when twerking around tree saplings that the trees grow after a certain time/number of twerks

### Observed/Actual behavior

when twerking, getting the sound and the bubble/particles but trees do not grow

### Steps/models to reproduce

created several islands in bskyblock
planted several different types of saplings (birch, oak, dark oak, azalea)
set the number of twerks needed in the config to 3
twerked for about 50 times
no growth

### BentoBox version

14.10 18:20:03 [Server] INFO BentoBox version: 1.24.1
14.10 18:20:03 [Server] INFO Database: JSON
14.10 18:20:03 [Server] INFO Loaded Game Worlds:
14.10 18:20:03 [Server] INFO bskyblock_world (BSkyBlock): Overworld, Nether, The End
14.10 18:20:03 [Server] INFO Loaded Addons:
14.10 18:20:03 [Server] INFO Bank 1.7.0 (ENABLED)
14.10 18:20:03 [Server] INFO Biomes 2.1.1 (ENABLED)
14.10 18:20:03 [Server] INFO Border 4.1.1 (ENABLED)
14.10 18:20:03 [Server] INFO BSkyBlock 1.16.1 (ENABLED)
14.10 18:20:03 [Server] INFO Challenges 1.2.0 (ENABLED)
14.10 18:20:03 [Server] INFO ControlPanel 1.13.0 (ENABLED)
14.10 18:20:03 [Server] INFO DimensionalTrees 1.6.0 (ENABLED)
14.10 18:20:03 [Server] INFO DragonFights 1.4.4 (ERROR)
14.10 18:20:03 [Server] INFO ExtraMobs 1.12 (ENABLED)
14.10 18:20:03 [Server] INFO Level 2.11.0 (ENABLED)
14.10 18:20:03 [Server] INFO Limits 1.19.1 (ENABLED)
14.10 18:20:03 [Server] INFO MagicCobblestoneGenerator 2.5.1 (ENABLED)
14.10 18:20:03 [Server] INFO RoseStackerHook 1.0.0 (ENABLED)
14.10 18:20:03 [Server] INFO TwerkingForTrees 1.4.3 (ENABLED)
14.10 18:20:03 [Server] INFO Upgrades 0.3.0-SNAPSHOT-b130 (ENABLED)
14.10 18:20:03 [Server] INFO Visit 1.6.0 (ENABLED)

### Plugin list

14.10 18:21:27 [Server] INFO Server Plugins (53):
14.10 18:21:27 [Server] INFO Paper Plugins:
14.10 18:21:27 [Server] INFO - EconomyShopGUI, RoseStacker
14.10 18:21:27 [Server] INFO Bukkit Plugins:
14.10 18:21:27 [Server] INFO - AuctionHouse, BentoBox, BentoBox-Bank, BentoBox-Biomes, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-Level, BentoBox-Limits, BentoBox-MagicCobblestoneGenerator, BentoBox-Visit
14.10 18:21:27 [Server] INFO BungeeGuard, ChunkCollector, Citizens, CoreProtect, CraftingStore, DecentHolograms, DeluxeSellwands, Denizen, DropEdit2, dtlTraders
14.10 18:21:27 [Server] INFO Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, F3NPerm, JetsMinions, LiteBans, LuckPerms, Multiverse-Core, MysqlPlayerDataBridge
14.10 18:21:27 [Server] INFO NexEngine, OpenInv, PlaceholderAPI, Pladdon, PlayerVaults, ProtocolLib, PWarp, RHLeafDecay, ShulkerPacks, SimplePortals
14.10 18:21:27 [Server] INFO SuperVanish, TabTPS, *TimelyActions, TitleManager, TradeSystem, Vault, VaultChatFormatter, VoidGen, WorldEdit, WorldGuard
14.10 18:21:27 [Server] INFO WorldGuardExtraFlags

**Comment by tastybento** [comment]
[Version 1.4.4](https://github.com/BentoBoxWorld/TwerkingForTrees/releases/tag/1.4.4) in my testing works. Please try it.
