### ISSUE TITLE
Twerking eats saplings.

### ISSUE THREAD

**Issue by MagmaSlime123** [BentoBoxWorld/TwerkingForTrees#4]
#### Describe the bug

Trees/Crops dissapear upon fully growing via twerking.

#### Steps to reproduce the behavior

Plant any sapling/crop, twerk, inspect results.

#### Expected behavior

The tree/crops growing, and not dissapearing.

### Environment
![2019-12-15_07 32 53](https://user-images.githubusercontent.com/51277766/70864994-1eccde00-1f0d-11ea-9948-f85ba8b01d65.png)

##### BentoBox Version (Mandatory)

![2019-12-15_07 33 45](https://user-images.githubusercontent.com/51277766/70865002-3efc9d00-1f0d-11ea-8b4e-31d2ea1fa4c1.png)

### Additional context (Optional)

After twerking, as you can see, tree completely dissapears. No grown tree, just a bunch of flame/smoke particles.

**Comment by tastybento** [comment]
Hmm, weird. It looks like it tried to grow, but couldn't. I'll investigate.

**Comment by tastybento** [comment]
Okay, fixed. If the tree cannot grow, then it won't consume the saplings. That'll mean that it might take longer to grow, or may never be able to grow. It'll depend on whether there's enough room or not.
